### ISSUE TITLE
estudo de Python, Flask, e API rest

### ISSUE THREAD

**Issue by cjjcastro** [ds-feudo-rosa/backend#5]

**Comment by daniel-de-sousa** [comment]
Cleber.
Dei uma estuda sobre API e REST.
Pelo que eu entendi, para utilizar o REST basca fazer usar as mecâncias do protocolo HTTP? Tipo o Get e o Post?
Também vi algo relacionado as URIs.
Enrão no caso, ao utilizar o REST, faríamos uma requisição na web para achar o site que contem a nóticia utilizando o HTTP, através do GET e armazenar no nosso banco de dados e depois usar o POST e mostrar na nossa API?

**Comment by cjjcastro** [comment]
o REST é o padrão que utilizaremos nas requisições http, cada um dos métodos possuem suas funções, seja para atualizar, inserir ou retornar um dado
